### ISSUE TITLE
Installation issue with Laravel

### ISSUE THREAD

**Issue by tyler36** [theseer/phpdox#282]
I'd like to use phpdox on a laravel project I'm working on.

I've installed laravel using the [Via Composer Create-Project](https://laravel.com/docs/master/installation) method and get version 5.2.39. To complete the installation, I run:
```
composer update
```

If i then run:
```
composer require "theseer/phpdox" 
```
.... I get the following error
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: nikic/php-parser[v1.3.0, v2.1.0].
    - Can only install one of: nikic/php-parser[v2.1.0, v1.3.0].
    - Can only install one of: nikic/php-parser[v1.3.0, v2.1.0].
    - theseer/phpdox 0.8.1.1 requires nikic/php-parser =1.3.0 -> satisfiable by nikic/php-parser[v1.3.0].
    - Installation request for theseer/phpdox 0.8.1.1 -> satisfiable by theseer/phpdox[0.8.1.1].
    - Installation request for nikic/php-parser (locked at v2.1.0) -> satisfiable by nikic/php-parser[v2.1.0].
```

Is there anything I can do to make it work?

Seems like an extension to [Issue 173](https://github.com/theseer/phpdox/issues/173), [Issue 256](https://github.com/theseer/phpdox/issues/256)

**Comment by theseer** [comment]
Please consider using the phar distributed version if phpDox.

The composer output shown above says php-parser is "locked" at 2.1.0, phpDox 0.8 was build against version 1.3.0.  If you must use composer, try using master - which uses 2.0.0 until i have time to look into this some more.

**Comment by theseer** [comment]
Not sure if that fixes your issue but I just released phpDox 0.9.0 which uses PHPParser 3.0.0 (alpha1).

**Comment by tyler36** [comment]
Thanks for taking the time to make the updates.
Unfortunately, I'm still getting the same type of error
```
  Problem 1
    - Installation request for theseer/phpdox ^0.9.0 -> satisfiable by theseer/phpdox[0.9.0].
    - Conclusion: remove nikic/php-parser v2.1.0
    - Conclusion: don't install nikic/php-parser v2.1.0
    - theseer/phpdox 0.9.0 requires nikic/php-parser 3.0.* -> satisfiable by nikic/php-parser[3.0.x-dev, v3.0.0alpha1].
    - Can only install one of: nikic/php-parser[3.0.x-dev, v2.1.0].
    - Can only install one of: nikic/php-parser[v3.0.0alpha1, v2.1.0].
    - Installation request for nikic/php-parser (locked at v2.1.0) -> satisfiable by nikic/php-parser[v2.1.0].
```

**Comment by tyler36** [comment]
Laravel 5.3 has just been released so I thought I'd give that one shot, however ...
```
  Problem 1
    - Installation request for theseer/phpdox ^0.9.0 -> satisfiable by theseer/phpdox[0.9.0].
    - theseer/phpdox 0.9.0 requires nikic/php-parser 3.0.* -> satisfiable by nikic/php-parser[3.0.x-dev, v3.0.0alpha1] but these conflict with your requirements or minimum-stability.
```

So I tried adding the following to composer ...
```
        "nikic/php-parser": "@dev",
        "theseer/phpdox": "^0.9"
```
... but just got more errors ...
```
  Problem 1
    - Conclusion: remove laravel/framework v5.3.4
    - Conclusion: don't install laravel/framework v5.3.4
    - Conclusion: don't install laravel/framework v5.3.3
    - Conclusion: don't install laravel/framework v5.3.2
    - Conclusion: don't install laravel/framework v5.3.1
    - Installation request for theseer/phpdox ^0.9 -> satisfiable by theseer/phpdox[0.9.0].
    - Installation request for laravel/framework 5.3.* -> satisfiable by laravel/framework[v5.3.0, v5.3.1, v5.3.2, v5.3.3, v5.3.4].
    - laravel/framework v5.3.0 requires psy/psysh 0.7.* -> satisfiable by psy/psysh[v0.7.2, v0.7.0, v0.7.1].
    - psy/psysh v0.7.2 requires nikic/php-parser ^1.2.1|~2.0 -> satisfiable by nikic/php-parser[v2.1.0, 1.x-dev, 2.x-dev, v1.2.1, v1.2.2, v1.3.0, v1.4.0, v1.4.1, v2.0.0, v2.0.0alpha1, v2.0.0beta1, v2.0.1].
    - psy/psysh v0.7.0 requires nikic/php-parser ^1.2.1|~2.0 -> satisfiable by nikic/php-parser[v2.1.0, 1.x-dev, 2.x-dev, v1.2.1, v1.2.2, v1.3.0, v1.4.0, v1.4.1, v2.0.0, v2.0.0alpha1, v2.0.0beta1, v2.0.1].
    - psy/psysh v0.7.1 requires nikic/php-parser ^1.2.1|~2.0 -> satisfiable by nikic/php-parser[v2.1.0, 1.x-dev, 2.x-dev, v1.2.1, v1.2.2, v1.3.0, v1.4.0, v1.4.1, v2.0.0, v2.0.0alpha1, v2.0.0beta1, v2.0.1].
    - psy/psysh v0.7.2 requires nikic/php-parser ^1.2.1|~2.0 -> satisfiable by nikic/php-parser[v2.1.0, 1.x-dev, 2.x-dev, v1.2.1, v1.2.2, v1.3.0, v1.4.0, v1.4.1, v2.0.0, v2.0.0alpha1, v2.0.0beta1, v2.0.1].
    - Can only install one of: nikic/php-parser[v3.0.0alpha1, 1.x-dev].
    - Can only install one of: nikic/php-parser[v3.0.0alpha1, 2.x-dev].
    - Can only install one of: nikic/php-parser[v3.0.0alpha1, v1.2.1].
    - Can only install one of: nikic/php-parser[v3.0.0alpha1, v1.2.2].
    - Can only install one of: nikic/php-parser[v3.0.0alpha1, v1.3.0].
    - Can only install one of: nikic/php-parser[v3.0.0alpha1, v1.4.0].
    - Can only install one of: nikic/php-parser[v3.0.0alpha1, v1.4.1].
    - Can only install one of: nikic/php-parser[v3.0.0alpha1, v2.0.0].
    - Can only install one of: nikic/php-parser[v3.0.0alpha1, v2.0.0alpha1].
    - Can only install one of: nikic/php-parser[v3.0.0alpha1, v2.0.0beta1].
    - Can only install one of: nikic/php-parser[v3.0.0alpha1, v2.0.1].
    - Can only install one of: nikic/php-parser[v3.0.0alpha1, v2.1.0].
    - Can only install one of: nikic/php-parser[v3.0.0alpha1, v2.1.0].
    - theseer/phpdox 0.9.0 requires nikic/php-parser 3.0.* -> satisfiable by nikic/php-parser[3.0.x-dev, v3.0.0alpha1].
    - don't install nikic/php-parser 3.0.x-dev|install nikic/php-parser dev-master
    - Conclusion: don't install nikic/php-parser dev-master
```

**Comment by tyler36** [comment]
I tried using the PHAR version as suggested and it works so feel free to close this issue if you would prefer.


Thanks again the package and for you help

**Comment by VEBERArnaud** [comment]
This is a ```(composer) minimum-stability``` issue
In composer, the default value for [```minimum-stability```](https://getcomposer.org/doc/04-schema.md#minimum-stability) is ```stable``` 

Here, ```theseer/phpdox 0.9.0``` requires ```nikic/php-parser 3.0.*``` but ```nikic/php-parser```has no stable release matching ```3.0.*```, only [pre-release](https://github.com/nikic/PHP-Parser/releases)

---

@tyler36, you can set the ```minimum-stability``` to ```dev``` in your ```composer.json``` to workaround this problem. But this is not a good idea, since it will install matching dev releases of your dependencies.

---

@theseer, you should change the 0.9.0 release to pre-release
I just tried a ```composer require theseer/phpdox``` and it failed installing because he tried to install the latest ~~stable~~ release, matching```0.9.0```

**Comment by theseer** [comment]
@VEBERArnaud Thank you for the helpful input! But why would I need to change a phpDox release just because it uses a pre-release as one of it's dependencies? And how would that fix the underlying problem the OP has? As far as I understand it, you'd still get dev-stability all over the place if you'd use the 0.9.0 release or have the previous issues if you go for 0.8.x...

**Comment by theseer** [comment]
I still think this mess is the result of a fundamental design flaw in composer's implementation: Not distinguishing between runtime (=application) dependencies and buildtime dependencies. Even more, dependencies of a tool should never conflict with dependencies of another tool as they are private to the tool. If composer would honor this sepration of concerns, this problem wouldn't exist.

As I don't see anything I could do within phpDox other than recommending the PHAR distribution and advocating against using composer to install tools, I'll close this issue.
